### crear tipo residencias
POST http://localhost:8080/api/residencias/tipos/crear
Content-Type: application/json

{
  "descripcion": "edificio",
  "precioKw": 5.48
}

### crea abonados
POST http://localhost:8080/api/abonados/crear
Content-Type: application/json

{
  "dni": "080120021990",
  "nombre": "thomas",
  "apellido": "edison",
  "telefono": "88673324",
  "tiposResidencia": {
    "idTipoResidencia": 1,
    "descripcion": "residencial",
    "precioKw": 4.56
  },
  "facturacion": []
}

### obtiene abonado
GET http://localhost:8080/api/abonados/080119902024 